name: Pull Request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
on:
  pull_request:

jobs:
  service:
    name: Validate Pull Request
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Validate
        run: npm run validate
