name: Prerelease
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
on:
  pull_request:

jobs:
  publish_prerelease:
    name: Publish Prerelease
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      actions: read
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify Change File Exists
        run: npm run checkchange

      - name: Publish Prerelease
        run: |
          COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          COMMIT_SHA_SHORT=$(git rev-parse --short "$COMMIT_SHA")
          npm run release -- --token "$NODE_AUTH_TOKEN" --no-push --prerelease-prefix $COMMIT_SHA_SHORT --tag prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
